// Generated by build_audio.py -- do not edit by hand.
const SAMPLES = {
  "best": {
    "systems": [
      "reference",
      "dualmono",
      "s3a",
      "diffstereo",
      "ours"
    ],
    "labels": [
      "Reference",
      "Degraded (Mono)",
      "S3A",
      "DiffStereo",
      "AURA (ours)"
    ],
    "clips": [
      {
        "id": "c01",
        "title": "Secretariat - Over The Top",
        "excerpt": "2:08",
        "dir": "audio/best/c01"
      },
      {
        "id": "c02",
        "title": "Enda Reilly - Cur An Long Ag Seol",
        "excerpt": "1:26",
        "dir": "audio/best/c02"
      },
      {
        "id": "c03",
        "title": "Ben Carrigan - We'll Talk About It All Tonight",
        "excerpt": "1:49",
        "dir": "audio/best/c03"
      },
      {
        "id": "c04",
        "title": "Secretariat - Over The Top",
        "excerpt": "2:38",
        "dir": "audio/best/c04"
      },
      {
        "id": "c05",
        "title": "AM Contra - Heart Peripheral",
        "excerpt": "3:11",
        "dir": "audio/best/c05"
      },
      {
        "id": "c06",
        "title": "Secretariat - Borderline",
        "excerpt": "3:19",
        "dir": "audio/best/c06"
      },
      {
        "id": "c07",
        "title": "AM Contra - Heart Peripheral",
        "excerpt": "1:25",
        "dir": "audio/best/c07"
      },
      {
        "id": "c08",
        "title": "The Easton Ellises (Baumi) - SDRNR",
        "excerpt": "0:52",
        "dir": "audio/best/c08"
      },
      {
        "id": "c09",
        "title": "We Fell From The Sky - Not You",
        "excerpt": "2:04",
        "dir": "audio/best/c09"
      },
      {
        "id": "c10",
        "title": "Georgia Wonder - Siren",
        "excerpt": "1:16",
        "dir": "audio/best/c10"
      }
    ]
  },
  "mychoice": {
    "systems": [
      "reference",
      "dualmono",
      "s3a",
      "diffstereo",
      "mono2ps",
      "ours"
    ],
    "labels": [
      "Reference",
      "Degraded (Mono)",
      "S3A",
      "DiffStereo",
      "Parametric Stereo",
      "AURA (ours)"
    ],
    "clips": [
      {
        "id": "c01",
        "title": "clip01_BKS_-_Bulldozer__0114.50",
        "excerpt": "1:54",
        "dir": "audio/mychoice/c01"
      },
      {
        "id": "c02",
        "title": "clip02_Arise_-_Run_Run_Run__0016.00",
        "excerpt": "0:16",
        "dir": "audio/mychoice/c02"
      },
      {
        "id": "c03",
        "title": "clip03_BKS_-_Too_Much__0046.50",
        "excerpt": "0:46",
        "dir": "audio/mychoice/c03"
      },
      {
        "id": "c04",
        "title": "clip04_Moosmusic_-_Big_Dummy_Shake__0065.50",
        "excerpt": "1:05",
        "dir": "audio/mychoice/c04"
      },
      {
        "id": "c05",
        "title": "clip05_AM_Contra_-_Heart_Peripheral__0085.50",
        "excerpt": "1:25",
        "dir": "audio/mychoice/c05"
      },
      {
        "id": "c06",
        "title": "clip06_Ben_Carrigan_-_We'll_Talk_About_It_All_Tonight__0092.50",
        "excerpt": "1:32",
        "dir": "audio/mychoice/c06"
      },
      {
        "id": "c07",
        "title": "clip07_Ben_Carrigan_-_We'll_Talk_About_It_All_Tonight__0109.00",
        "excerpt": "1:49",
        "dir": "audio/mychoice/c07"
      },
      {
        "id": "c08",
        "title": "clip08_AM_Contra_-_Heart_Peripheral__0191.50",
        "excerpt": "3:11",
        "dir": "audio/mychoice/c08"
      }
    ]
  },
  "lpf": {
    "systems": [
      "reference",
      "degraded",
      "ours"
    ],
    "labels": [
      "Reference",
      "Degraded (low-pass mono)",
      "AURA (ours)"
    ],
    "clips": [
      {
        "id": "c01",
        "title": "Ben Carrigan - We'll Talk About It All Tonight",
        "excerpt": "1:49",
        "dir": "audio/lpf/c01"
      },
      {
        "id": "c02",
        "title": "Georgia Wonder - Siren",
        "excerpt": "5:45",
        "dir": "audio/lpf/c02"
      },
      {
        "id": "c03",
        "title": "The Mountaineering Club - Mallory",
        "excerpt": "3:47",
        "dir": "audio/lpf/c03"
      },
      {
        "id": "c04",
        "title": "AM Contra - Heart Peripheral",
        "excerpt": "3:11",
        "dir": "audio/lpf/c04"
      },
      {
        "id": "c05",
        "title": "AM Contra - Heart Peripheral",
        "excerpt": "1:53",
        "dir": "audio/lpf/c05"
      },
      {
        "id": "c06",
        "title": "AM Contra - Heart Peripheral",
        "excerpt": "1:25",
        "dir": "audio/lpf/c06"
      },
      {
        "id": "c07",
        "title": "Girls Under Glass - We Feel Alright",
        "excerpt": "0:30",
        "dir": "audio/lpf/c07"
      }
    ]
  }
};
